//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.DroneSimMessages
{
    [Serializable]
    public class Drone_ControlMsg : Message
    {
        public const string k_RosMessageName = "drone_sim_messages/Drone_Control";
        public override string RosMessageName => k_RosMessageName;

        //  ROS2 Message for Drone Control
        public HeaderMsg header;
        public Geometry.TwistMsg twist;
        //  Description below is the definition of the twist message
        //    Vector3 linear
        //     float64 x  # Forward/Backward
        //     float64 y  # Left/Right
        //     float64 z  # Up/Down
        //   Vector3 angular
        //     float64 x  # Roll
        //     float64 y  # Pitch
        //     float64 z  # Yaw (Yaw left/Yaw right)

        public Drone_ControlMsg()
        {
            this.header = new HeaderMsg();
            this.twist = new Geometry.TwistMsg();
        }

        public Drone_ControlMsg(HeaderMsg header, Geometry.TwistMsg twist)
        {
            this.header = header;
            this.twist = twist;
        }

        public static Drone_ControlMsg Deserialize(MessageDeserializer deserializer) => new Drone_ControlMsg(deserializer);

        private Drone_ControlMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "Drone_ControlMsg: " +
            "\nheader: " + header.ToString() +
            "\ntwist: " + twist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
