//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DroneSimMessages
{
    [Serializable]
    public class DroneStatusMsg : Message
    {
        public const string k_RosMessageName = "drone_sim_messages/DroneStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Drone Status Data
        public string id;
        public bool active;

        public DroneStatusMsg()
        {
            this.id = "";
            this.active = false;
        }

        public DroneStatusMsg(string id, bool active)
        {
            this.id = id;
            this.active = active;
        }

        public static DroneStatusMsg Deserialize(MessageDeserializer deserializer) => new DroneStatusMsg(deserializer);

        private DroneStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.active);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.active);
        }

        public override string ToString()
        {
            return "DroneStatusMsg: " +
            "\nid: " + id.ToString() +
            "\nactive: " + active.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
