//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DroneSimMessages
{
    [Serializable]
    public class SessionInfoMsg : Message
    {
        public const string k_RosMessageName = "drone_sim_messages/SessionInfo";
        public override string RosMessageName => k_RosMessageName;

        //  Session Info Data
        public bool session_ended;
        public int stage;
        public int run_count;

        public SessionInfoMsg()
        {
            this.session_ended = false;
            this.stage = 0;
            this.run_count = 0;
        }

        public SessionInfoMsg(bool session_ended, int stage, int run_count)
        {
            this.session_ended = session_ended;
            this.stage = stage;
            this.run_count = run_count;
        }

        public static SessionInfoMsg Deserialize(MessageDeserializer deserializer) => new SessionInfoMsg(deserializer);

        private SessionInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.session_ended);
            deserializer.Read(out this.stage);
            deserializer.Read(out this.run_count);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.session_ended);
            serializer.Write(this.stage);
            serializer.Write(this.run_count);
        }

        public override string ToString()
        {
            return "SessionInfoMsg: " +
            "\nsession_ended: " + session_ended.ToString() +
            "\nstage: " + stage.ToString() +
            "\nrun_count: " + run_count.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
